### PR TITLE
Don't use Unicode when querying basedir, document preference for UTF8.

### LINKED ISSUE #90: capture basedir
```
bash-4.3$ emacs --version
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
bash-4.3$ julia --version
julia version 1.4.2
bash-4.3$ which julia
/usr/bin/julia
bash-4.3$ tree -L 1 ~/.emacs.d/elpa
/home/eric/.emacs.d/elpa
|-- archives
|-- ess-18.10.2
|-- gnupg
|-- julia-mode-0.4
|-- julia-repl-1.2.0
`-- s-1.12.0

6 directories, 0 files
bash-4.3$ 
```

`M-x julia-repl` generates in a &ast;Warnings&ast; buffer the below.

Warning (emacs): could not capture basedir for Julia executable julia

### PR DESCRIPTION
**Pull request by tpapp**
Fixes #90.

### CODE REVIEW

**Comment by tpapp** [comment]
@apparluk, can you please test if this fixes #90 for you?

**Comment by apparluk** [comment]
README.md

Placing the following line in ~/.emacs.d/init.el had no effect on the GUI Emacs julia-repl unicode rendering.

```emacs-lisp
(set-language-environment "UTF-8")
```
julia-repl.el

As expected with converting from `≤` to `<=` and starting the GUI Emacs then `M-x julia-repl` the **&ast;Warnings&ast;** buffer did not appear.

**Comment by tpapp** [comment]
I am surprised by that, as `set-language-environment` usually sets the coding system, eg see https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/international/mule-cmds.el#n1905.

**Comment by apparluk** [comment]
The following added to ~/.emacs.d/init.el resulted in no **&ast;Warnings&ast;** in GUI Emacs due to `≤`.

```elisp
(if (display-graphic-p)
(set-locale-environment "da_DK.UTF-8"))
```

**Pull request merged**
