### PR TITLE
Make "C-c C-z" switch back and forth between the script and REPL buffers

### PR DESCRIPTION
**Pull request by wentasah**
[julia-vterm.el](https://github.com/shg/julia-vterm.el) implements this and I miss it in julia-repl.

### CODE REVIEW

**Comment by tpapp** [comment]
Thanks for the nice contribution. This looks fine, I will be testing it next week and then I will merge. (Feel free to ping if I forget).

**Comment by wentasah** [comment]
Ping :-)

**Comment by tpapp** [comment]
Sorry, something came up and I haven't had time to evaluate this. Will do so next week.

**Comment by tpapp** [comment]
Thanks for your patience. I found this to be a very nice feature and appreciate the contribution.

**Pull request merged**
