### PR TITLE
Fix up error regexps.

### PR DESCRIPTION
**Pull request by tpapp**
Remove legacy ones (still available with an option), test.

### CODE REVIEW

**Comment by tpapp** [comment]
@PetrKryslUCSD, this should fix the clickable locations, cf your comment https://github.com/tpapp/julia-repl/pull/107#issuecomment-2537407628. It would be great if you could test it.

**Comment by PetrKryslUCSD** [comment]
Thanks!
The first two lines are NOT clickable:
image

**Comment by tpapp** [comment]
@PetrKryslUCSD: I tweaked the regexps to include `_`, can you please check again?

**Comment by tpapp** [comment]
Thanks for checking, I really appreciate it. Will merge and release now.

**Pull request merged**
